---
title: "Center Differentiation V.S. Forward Differentiation Outcomes"
author: "Yixuan Yang"
date: "3/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
rm(list = ls()) # clean current data
# import packages
library(tidyverse)
source("Functions.R")
```


```{r, include=FALSE}
# Store center and forward data
load('../Rdata/CenterFish.Rdata')
IGC1_Full_Center = IGC1_Full
IGC1_Full_igcOmega_Center = IGC1_Full_igcOmega
load('../Rdata/ForwardFish.Rdata')
IGC1_Full_Forward = IGC1_Full
IGC1_Full_igcOmega_Forward = IGC1_Full_igcOmega
```

# Look at the difference between log likelihood
## one omega model
```{r, echo=FALSE}
sort(IGC1_Full_Center$ll - IGC1_Full_Forward$ll)
hist(IGC1_Full_Center$ll - IGC1_Full_Forward$ll,
     main = "likelihood difference in one omega model")
```




## Seperate omega model
```{r, echo=FALSE}
sort(IGC1_Full_igcOmega_Center$ll - IGC1_Full_igcOmega_Forward$ll)
hist(IGC1_Full_igcOmega_Center$ll - IGC1_Full_igcOmega_Forward$ll,
     main = "likelihood difference in seperate omega model")
```

Data under each case doesn't behave the same