---
title: "IGC Proportion"
author: "Yixuan Yang"
date: "3/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
rm(list = ls()) # clean current data
# import packages
library(tidyverse)
library(gt)
source("Functions.R")
load('../Rdata/Fish.Rdata')
```

```{r, include=FALSE}
# Calculate proportion
igc.proportion <- function(dataset){
    out = c()
    namelist <- colnames(dataset)
    one2two <- c()
    two2one <- c()
    mut <- c()
    for(i in namelist){
      if(str_detect(i,"1->2")){
        if (str_detect(i,"N0")==FALSE){
          one2two <- append(one2two,i)
        }
      }
      
      if(str_detect(i,"2->1")){
        if (str_detect(i,"N0")==FALSE){
          two2one <- append(two2one,i)
        }
      }
      
      if(str_detect(i,"mut")){
        if (str_detect(i,"N0")==FALSE){
          mut <- append(mut,i)
        }
      }
    }
    for(j in 1:dim(dataset)[1]){
      one2twoSum <- sum(dataset[j, one2two])
      two2oneSum <- sum(dataset[j, two2one])
      mutSum <- sum(dataset[j, mut])
      num <- sum(one2twoSum, two2oneSum)
      den <- sum(num, mutSum)
      p = num/den
      out = rbind(out,c(rownames(dataset)[j], p))
    }
    out = data.frame(out)
    names(out) = c("names","proportion")
    out[,2] = as.numeric(out[,2])
    out = data.frame(out, row.names = 1)
    return(out)
}
```

```{r, include=FALSE}
propIGCXiang = igc.proportion(IGC1_Full)
propIGChomo  = igc.proportion(IGC1_Full_Homo)
propIGChomo/propIGCXiang
```



