---
title: "Branch Length and Branch Tau Values in 45 Fish Data"
author: "Yixuan Yang"
date: "3/17/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
rm(list = ls())
load('../Rdata/ForwardFish.Rdata')
library(tidyverse)
library(kableExtra)
```

```{r, include=FALSE}
IGC1_Full = t(IGC1_Full)
IGC1_Btau <- subset(IGC1_Full, str_detect(rownames(IGC1_Full), "tau"))
```

```{r, include=FALSE}
IGC1_BLength <- subset(IGC1_Full, str_detect(rownames(IGC1_Full), 
                      c("tau|mut|1->2|2->1"), negate = TRUE))

IGC1_BLength <- IGC1_BLength[9:nrow(IGC1_BLength),]

```

```{r, include=FALSE}
# function for finding outliers
findOutlier <- function(data, standard){
  m <- c()
  for (i in 1:dim(data)[1]){
    for (j in 1:dim(data)[2]){
      if(is.na(data[i,j])==FALSE){
        if(data[i,j] > standard){
        row <- c(colnames(data)[j], rownames(data)[i], data[i,j])
        m <- rbind(m, row)
        }
      }
    }
  }
  row.names(m) <- NULL
  m <- cbind(1:dim(m)[1],m)
  return(m)
}
```

```{r, echo=FALSE}
branch_length = findOutlier(IGC1_BLength, 1)[1:9,2:4]
branch_length_sorted = branch_length[order(branch_length[,3], decreasing = T),]
colnames(branch_length_sorted) = c("Pillar","branch","branch_length")
kable(branch_length_sorted, caption = "According to the table, we decided to exclude data with significant long branch length. We selected data with branch length greater than 2.")
```

```{r, echo=FALSE}
branch_tau = findOutlier(IGC1_Btau, 0.5)
branch_tau_sorted = branch_tau[order(branch_tau[,4], decreasing = T),2:4]
colnames(branch_tau_sorted) = c("Pillar","Branch", "tau_value")
kable(branch_tau_sorted, caption = "This table explained why we exclude data Pillar3994.")
```
