---
title: "Likelihood Ratio Test"
author: "Yixuan Yang"
date: "3/19/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
rm(list = ls()) # clean work space
load('../Rdata/CenterFish.Rdata')
library(tidyverse)
library(kableExtra)
```

# Likelihood ratio tests

```{r, include=FALSE}
llTest = data.frame(IGC1_Full$ll, IGC1_Full_igcOmega$ll)
colnames(llTest) = c("oldModel", "newModel")
plot1 = ggplot() +
  geom_point(data = llTest, aes(x = oldModel, y = newModel)) +
  geom_abline(slope = 1)

plot2 = ggplot() +
  geom_histogram(data = llTest, aes(x = newModel - oldModel))

gridExtra::grid.arrange(plot1, plot2, ncol = 2)
```

```{r, include=FALSE}
two_times_llDif = 2*(IGC1_Full_igcOmega$ll - IGC1_Full$ll)
p_values = 1-pchisq(two_times_llDif, df=1) %>% round(4)
llTest.table = data.frame(IGC1_Full_igcOmega$tau, IGC1_Full$tau,
                          IGC1_Full_igcOmega$omega, IGC1_Full$omega,
                          IGC1_Full_igcOmega$IGC_omega / IGC1_Full_igcOmega$tau,
                          two_times_llDif, p_values)
rownames(llTest.table) = rownames(IGC1_Full)
llTest.table[,"reject at 0.05"] = llTest.table$p_values < 0.05
colnames(llTest.table)[1:5] = c("new.tau", "old.tau", "new.omega", "old.omega", "igc.omega/new.tau")

# some extra code
# install.packages("magick")
# install.packages("webshot")
# webshot::install_phantomjs()

kable(llTest.table, "latex", booktabs = T, 
      caption = "Likelihood Ratio Test: one omega model v.s. model with igc omega") %>% 
  row_spec(which(llTest.table$`igc.omega/new.tau` < 1), color="red") %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  save_kable("../summary/llTestTable.pdf")
```



```{r, echo=FALSE}
two_times_llDif = 2*(IGC1_Full_igcOmega$ll - IGC1_Full_igcOmega0$ll)
p_values = 1-pchisq(two_times_llDif, df=1) %>% round(4)
llTest.table = data.frame(IGC1_Full_igcOmega$tau, IGC1_Full_igcOmega0$tau,
                          IGC1_Full_igcOmega$omega, IGC1_Full_igcOmega0$omega,
                          IGC1_Full_igcOmega$IGC_omega / IGC1_Full_igcOmega$tau,
                          two_times_llDif, p_values)
rownames(llTest.table) = rownames(IGC1_Full)
llTest.table[,"reject at 0.05"] = llTest.table$p_values < 0.05
colnames(llTest.table)[1:5] = c("tau.alter", "tau.null", "omega.alter", "omega.null", "omega'")

# some extra code
# install.packages("magick")
# install.packages("webshot")
# webshot::install_phantomjs()

kable(llTest.table, "latex", booktabs = T, 
      caption = "Likelihood Ratio Test: tau'=0 vs tau' is free") %>% 
  row_spec(which(llTest.table$p_values > 0.05), color="red") %>%
  kable_styling(latex_options = c("striped", "scale_down"))
  #save_kable("../summary/test_IGC.pdf")
```



```{r, echo=FALSE}
two_times_llDif = 2*(IGC1_Full_igcOmega0$ll - IGC1_Full_igcOmega0_tau0$ll)
p_values = 1-pchisq(two_times_llDif, df=1) %>% round(4)
llTest.table = data.frame(IGC1_Full_igcOmega0$tau, IGC1_Full_igcOmega0_tau0$tau,
                          IGC1_Full_igcOmega0$omega, IGC1_Full_igcOmega0_tau0$omega,
                          # IGC1_Full_igcOmega$IGC_omega / IGC1_Full_igcOmega$tau,
                          two_times_llDif, p_values)
rownames(llTest.table) = rownames(IGC1_Full)
llTest.table[,"reject at 0.05"] = llTest.table$p_values < 0.05
colnames(llTest.table)[1:4] = c("tau.alter", "tau.null", "omega.alter", "omega.null")

# some extra code
# install.packages("magick")
# install.packages("webshot")
# webshot::install_phantomjs()

kable(llTest.table, "latex", booktabs = T, 
      caption = "Likelihood Ratio Test: tau=0, tau'=0 vs tau'=0") %>% 
  row_spec(which(llTest.table$p_values > 0.05), color="red") %>%
  kable_styling(latex_options = c("striped", "scale_down"))
  #save_kable("../summary/test_IGC.pdf")
```
