---
title: "MarchSummary"
author: "Yixuan Yang"
date: "3/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls()) # clean current data
# import packages
library(tidyverse)
library(kableExtra)
source("Functions.R")
```


```{r}
# read in data
## single analysis
### IGC1
path = 'inputFiles/SingleAnalysis/'
IGC1_Full = IGC_summary(str_c(path, 'IGC1_Full'))
IGC1_Full_Force = IGC_summary(str_c(path, 'IGC1_Full_Force'))
IGC1_Full_Force_igcOmega = IGC_summary(str_c(path, 'IGC1_Full_Force_igcOmega08'))
IGC1_Full_igcOmega = IGC_summary(str_c(path, 'IGC1_Full_igcOmega08'))
IGC1_Full_reparameter = IGC_summary(str_c(path, 'IGC1_Full_reparameter1'))
IGC1_Swap_Clock = IGC_summary(str_c(path, 'IGC1_Swap_Clock'))
IGC1_Unswap_Clock = IGC_summary(str_c(path, 'IGC1_Unswap_Clock'))
IGC1_Swap_Clock_igcOmega = IGC_summary(str_c(path, 'IGC1_Swap_Clock_igcOmega08'))
IGC1_Unswap_Clock_igcOmega = IGC_summary(str_c(path, 'IGC1_Unswap_Clock_igcOmega08'))
IGC1_Swap_Clock_reparameter = IGC_summary(str_c(path, 'IGC1_Swap_Clock_reparameter1'))
IGC1_Unswap_Clock_reparameter = IGC_summary(str_c(path, 'IGC1_Unswap_Clock_reparameter1'))
###IGC2
# IGC2_Full = IGC_summary(str_c(path, 'IGC2_Full'))
# IGC2_Full_Force = IGC_summary(str_c(path, 'IGC2_Full_Force'))
# IGC2_Full_Force_igcOmega = IGC_summary(str_c(path, 'IGC2_Full_Force_igcOmega08'))
# IGC2_Full_igcOmega = IGC_summary(str_c(path, 'IGC2_Full_igcOmega08'))
# IGC2_Full_reparameter = IGC_summary(str_c(path, 'IGC2_Full_reparameter2'))
# IGC2_Swap_Clock = IGC_summary(str_c(path, 'IGC2_Swap_Clock'))
# IGC2_Unswap_Clock = IGC_summary(str_c(path, 'IGC2_Unswap_Clock'))
# IGC2_Swap_Clock_igcOmega = IGC_summary(str_c(path, 'IGC2_Swap_Clock_igcOmega08'))
# IGC2_Unswap_Clock_igcOmega = IGC_summary(str_c(path, 'IGC2_Unswap_Clock_igcOmega08'))

path = 'inputFiles/JointAnalysis/'
Joint_2omega = joint_summary(str_c(path, 'Joint_2omega_newModel'))
Joint_igcOmega = joint_summary(str_c(path, 'Joint_igcOmega_newModel'))
Joint_omega = joint_summary(str_c(path, 'Joint_omega'))
Joint_omega_new = joint_summary(str_c(path, 'Joint_omega_newModel'))

save.image(file = "Fish.Rdata")
```


# Swap Test
```{r}
#IGC1
SwapTestRatio = data.frame(IGC1_Swap_Clock$tau, IGC1_Unswap_Clock$tau)
colnames(SwapTestRatio) <- c("Swap_tau", "Unswap_tau")
ggplot() +
  geom_point(data = SwapTestRatio, aes(x = Swap_tau, y = Unswap_tau)) +
  geom_abline(slope = 1) +
  labs(title = "Swap Test", subtitle = "for 45 fish data")

## Swap test with igc omega
SwapTestRatio = data.frame(IGC1_Swap_Clock_igcOmega$tau, IGC1_Unswap_Clock_igcOmega$tau)
colnames(SwapTestRatio) <- c("Swap_tau", "Unswap_tau")
ggplot() +
  geom_point(data = SwapTestRatio, aes(x = Swap_tau, y = Unswap_tau)) +
  geom_abline(slope = 1) +
  labs(title = "Swap Test in IGC omega model", subtitle = "for 45 fish data")

## Swap test with igc omega reparameter
SwapTestRatio = data.frame(IGC1_Swap_Clock_reparameter$tau, IGC1_Unswap_Clock_reparameter$tau)
colnames(SwapTestRatio) <- c("Swap_tau", "Unswap_tau")
ggplot() +
  geom_point(data = SwapTestRatio, aes(x = Swap_tau, y = Unswap_tau)) +
  geom_abline(slope = 1) +
  labs(title = "Swap Test in IGC omega model reparameter", subtitle = "for 45 fish data")

```

# Likelihood ratio test
compare between two model
```{r}
llTest = data.frame(IGC1_Full$ll, IGC1_Full_igcOmega$ll)
colnames(llTest) = c("oldModel", "newModel")
plot1 = ggplot() +
  geom_point(data = llTest, aes(x = oldModel, y = newModel)) +
  geom_abline(slope = 1)

plot2 = ggplot() +
  geom_histogram(data = llTest, aes(x = newModel - oldModel))

gridExtra::grid.arrange(plot1, plot2, ncol = 2)

two_times_ll = 2*(IGC1_Full_igcOmega$ll - IGC1_Full$ll)
p_values = 1-pchisq(two_times_ll, df=1) %>% round(4)
llTest.table = data.frame(IGC1_Full_igcOmega$tau, IGC1_Full$tau,
                          IGC1_Full_igcOmega$omega, IGC1_Full$omega,
                          IGC1_Full_igcOmega$IGC_omega,
                          two_times_ll, p_values)
rownames(llTest.table) = rownames(IGC1_Full)
llTest.table[,"reject at 0.05"] = llTest.table$p_values < 0.05
colnames(llTest.table)[1:5] = c("new.tau", "old.tau", "new.omega", "old.omega", "igc omega")

# some extra code
# install.packages("magick")
# install.packages("webshot")
# webshot::install_phantomjs()

kable(llTest.table, "latex", booktabs = T) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  save_kable("~/Downloads/llTestTable.pdf")
```


# Force $\tau$
```{r}
Force = data.frame(IGC1_Full$omega, IGC1_Full_Force$omega, IGC1_Full_Force_igcOmega$omega)
colnames(Force) = c("omega", "forceTau.omega", "new.forceTau.omega")
ggplot() +
  geom_point(data = Force, aes(x = forceTau.omega, y = omega)) +
  geom_abline(slope=1) +
  labs(title = "Force Tau")

ggplot() +
  geom_point(data = Force, aes(x = new.forceTau.omega, y = forceTau.omega)) +
  geom_abline(slope=1) +
  labs(title = "Force Tau", subtitle = "new model v.s. old model")
```

# IGC omega
```{r}
ggplot() +
  geom_histogram(data = IGC1_Full_igcOmega, aes(x = IGC_omega)) +
  labs(title = "IGC omega")

ggplot() +
  geom_histogram(data = IGC1_Full_reparameter, aes(x = tau_times_omega/tau)) +
  labs(title = "reparameter")
```