---
#title: "yeast_data"
output: pdf_document
#date: "2022-08-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
rm(list = ls())
library(tidyverse)
library(kableExtra)
source('Functions.R')
```

```{r, echo=FALSE}
path = '../input_files/yeast/Analysis/'
yeast_homo_forceTau = IGC_summary(str_c(path, 'yeast_forceTau_Homo'))
yeast_homo = IGC_summary(str_c(path, 'yeast_Homo'))
yeast_orig_forceTau = IGC_summary(str_c(path, 'yeast_forceTau_Original'))
yeast_orig = IGC_summary(str_c(path, 'yeast_Original'))
save.image(file = "../Rdata/yeast.Rdata")
```

```{r, echo=FALSE}
# Likelihood Difference
tb1 = data.frame(yeast_orig_forceTau$ll, yeast_orig$ll - yeast_orig_forceTau$ll, yeast_homo_forceTau$ll - yeast_orig_forceTau$ll, yeast_homo$ll - yeast_orig_forceTau$ll)
rownames(tb1) = gsub("_","|",rownames(yeast_orig))

tb1 %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
      caption = "Log likelihood difference to Xiang's original model without IGC event",
      col.names = linebreak(c("Orignal($\\tau=0$)", "Original", "Homogenizing($\\tau=0$)", "Homogenizing"))) %>%
  kable_styling(latex_options = c("striped")) %>%
  add_footnote(c("column 1 is the log-likelihood of Xiang's original model when no IGC event",
                 "column 2,3,4 are the log-likelihood from different model minus column 1"))

# omega values
tb2 = data.frame(yeast_orig_forceTau$omega,
                 yeast_orig$omega,
                 yeast_homo_forceTau$omega,
                 yeast_homo$omega,
                 yeast_homo_forceTau$homogenizing_omega,
                 yeast_homo$homogenizing_omega)
rownames(tb2) = gsub("_","|",rownames(yeast_orig))

tb2 %>% 
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
      caption = "Yeast data in homogenizing model (left two columns are omega value from Xiang's original model)",
      col.names = linebreak(c("$\\omega_{Xiang}(\\tau=0)$",
                              "$\\omega_{Xiang}$",
                              "$\\omega(\\tau=0)$",
                              "$\\omega$",
                              "$\\omega_{homo} (\\tau=0)$",
                              "$\\omega_{homo}$"))) %>%
  kable_styling(latex_options = c("striped")) %>%
  add_footnote(c("column 1 and 2 are omega values from Xiang's original model",
                 "colum 3,4,5,6 are omega values frome the homogenizing model",
                 "omega means the non-homogenizing omega",
                 "omega_homo means the homogenizing omega"))

tb3 = data.frame(yeast_orig$tau, yeast_homo$tau)
rownames(tb3) = gsub("_","|",rownames(yeast_orig))

tb3 %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
      caption = "Yeast data: tau value from different model",
      col.names = linebreak(c("$\\tau_{Xiang}$", "$\\tau_{homo}$"))) %>%
  kable_styling(latex_options = c("striped")) %>%
  add_footnote(c("column 1 is the tau value from Xiang's original model",
                 "column 2 is the tau value from the homogenizing model"))
```

